// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoLandMerged } from "./AutoLandMerged";
import type { AutoLandPhase } from "./AutoLandPhase";
import type { LandOutcome } from "./LandOutcome";
import type { LandSegment } from "./LandSegment";

/**
 * The job as a host renders it: published on every phase change and
 * answered whole when a surface reconnects.
 */
export type AutoLandState = { headBookmark: string, phase: AutoLandPhase, 
/**
 * Rounds that executed actions (merges, hand-offs, reconciles).
 */
rounds: number, 
/**
 * PRs confirmed merged so far, in the order the job saw them land.
 */
merged: Array<AutoLandMerged>, 
/**
 * The latest plan's segments — the same per-segment story the manual
 * land card renders.
 */
segments: Array<LandSegment>, 
/**
 * The last executed round's steps, for the job card.
 */
lastOutcome: LandOutcome | null, };
