// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoLandRecord } from "./AutoLandRecord";

/**
 * A record as a host answers it to a (re)connecting surface: `live`
 * distinguishes a record a thread is driving right now from one that
 * survived from an earlier session (or whose thread died) — the UI's
 * "interrupted — resume?" state is a non-terminal record that is not
 * live.
 */
export type AutoLandStatus = { record: AutoLandRecord, live: boolean, };
