// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutoLandState } from "./AutoLandState";

/**
 * The one-job record a host persists: the state plus which repo it
 * belongs to and when it was saved. Saved on every publish and loaded at
 * the next launch, so a waiting or parked job survives a restart as
 * resumable status; status only renders when the same repo is open
 * again, which is why the repo path rides along.
 */
export type AutoLandRecord = { version: number, 
/**
 * The repo the job was queued in (`RepoSnapshot::repo_path`).
 */
repoPath: string, state: AutoLandState, 
/**
 * Unix milliseconds of the save — the "as of" behind a restored
 * status.
 */
savedAtMs: bigint, };
