// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the job stands right now.
 */
export type AutoLandPhase = { "kind": "waiting", attention: boolean, reasons: Array<string>, } | { "kind": "round" } | { "kind": "done" } | { "kind": "failed", message: string, } | { "kind": "stopped" };
