// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A PR the job saw land — merged by a round or recognized as merged on
 * GitHub (auto-merge, the queue, or someone clicking the button).
 */
export type AutoLandMerged = { number: bigint, url: string, bookmark: string, };
