// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SyncState } from "./SyncState";

export type BookmarkState = { name: string, 
/**
 * Change id the bookmark points at.
 */
target: string, remote: string | null, sync: SyncState, isTrunk: boolean, 
/**
 * False only for the synthetic entry a remote-only trunk gets: with no
 * local bookmark behind it there is nothing to move, rename, or delete.
 */
isLocal: boolean, };
