// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChangedFile } from "./ChangedFile";

/**
 * Per-change data too expensive to compute for every node in a snapshot.
 * Fetched lazily when the UI inspects one change.
 */
export type ChangeDetail = { 
/**
 * Change id this detail was computed for, echoed back from the request.
 */
id: string, 
/**
 * Files changed relative to the parent tree(s), in repo path order.
 */
files: Array<ChangedFile>, 
/**
 * True when the file list was capped before the diff was exhausted.
 */
truncated: boolean, };
