// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiff } from "./FileDiff";

/**
 * The full content diff for one change, fetched lazily when the diff
 * surface renders a selection. Heavier than `ChangeDetail`: every file's
 * contents are materialized and diffed.
 */
export type ChangeDiff = { 
/**
 * Change id this diff was computed for, echoed back from the request.
 */
id: string, 
/**
 * Set when this diff compares against another change's tree instead of
 * the parent tree(s) — commit-to-commit or stack-relative comparison.
 * Echoes the requested from-change id back so the UI can match a
 * response to the comparison it currently shows.
 */
from: string | null, 
/**
 * Files changed relative to the parent tree(s), in repo path order.
 */
files: Array<FileDiff>, 
/**
 * True when the file list was capped before the diff was exhausted.
 */
truncated: boolean, };
