// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CI state of the PR's head commit, GitHub's own rollup across check runs
 * and commit statuses. `None` when nothing is configured.
 */
export type ChecksRollup = "passing" | "failing" | "pending" | "none";
