// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What one re-run request accomplished, for the UI to tell straight.
 */
export type CiRerunReport = { 
/**
 * Workflow runs whose failed jobs were sent back to work.
 */
rerun: Array<string>, 
/**
 * Failed runs GitHub refused to re-run (already re-running, logs
 * expired, …), as plain per-run stories.
 */
refused: Array<string>, };
