// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictKind } from "./ConflictKind";

export type ConflictItem = { id: string, kind: ConflictKind, 
/**
 * Plain-language explanation of what happened.
 */
summary: string, nodeId: string | null, path: string | null, };
