// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictKind } from "./ConflictKind";

export type ConflictItem = { id: string, kind: ConflictKind, 
/**
 * Plain-language explanation of what happened.
 */
summary: string, 
/**
 * The change the conflict lives in (file conflicts) or the stale
 * workspace's working copy, when that change is drawn in the snapshot.
 */
nodeId: string | null, 
/**
 * Conflicted file paths, repo-relative (file conflicts only). Lists
 * the tree's own unresolved entries — what `jj resolve --list` shows —
 * so a conflict inherited from a parent appears even though the
 * parent-relative diff would not mention the file.
 */
paths: Array<string>, 
/**
 * Count of conflicted paths dropped past the per-item cap.
 */
morePaths: number, 
/**
 * Change ids a conflicted bookmark resolved to (bookmark conflicts
 * only): the candidates the user can repoint it at.
 */
targets: Array<string>, 
/**
 * The workspace a stale-workspace item is about. The UI offers the
 * guided recovery only when this names the current workspace — the one
 * `update_stale_workspace` can act on.
 */
workspace: string | null, };
