// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLineKind } from "./DiffLineKind";
import type { DiffSegment } from "./DiffSegment";

export type DiffLine = { kind: DiffLineKind, 
/**
 * The line's text (without its trailing newline) split into intraline
 * segments; `changed` segments are the word-level differences inside a
 * modified run. A fully added/removed line is one changed segment.
 */
segments: Array<DiffSegment>, };
