// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

/**
 * One unified hunk: a run of changed lines plus surrounding context.
 */
export type DiffHunk = { 
/**
 * 1-based line number of the hunk's first line on the old side.
 */
oldStart: number, 
/**
 * 1-based line number of the hunk's first line on the new side.
 */
newStart: number, lines: Array<DiffLine>, };
