// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileDiffContent } from "./FileDiffContent";
import type { FileStatus } from "./FileStatus";

export type FileDiff = { 
/**
 * Repo-relative path, `/`-separated.
 */
path: string, status: FileStatus, 
/**
 * Source path when the file was renamed or copied from elsewhere.
 */
renamedFrom: string | null, hasConflict: boolean, content: FileDiffContent, };
