// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

/**
 * What the diff surface can render for one file. Conflicted files arrive as
 * `text` with jj's conflict markers materialized into the content.
 */
export type FileDiffContent = { "kind": "text", hunks: Array<DiffHunk>, truncated: boolean, } | { "kind": "binary" } | { "kind": "tooLarge" } | { "kind": "omitted" };
