// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForgeAuth } from "./ForgeAuth";
import type { ForgeRepo } from "./ForgeRepo";

/**
 * Everything the Publish surface needs to render the forge connection:
 * the detected repository plus authentication state.
 */
export type ForgeStatus = { 
/**
 * GitHub repo behind the open jj repo's preferred remote, when one is.
 */
repo: ForgeRepo | null, auth: ForgeAuth, };
