// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenSource } from "./TokenSource";

/**
 * Authentication state for the UI: which token would be used, and the
 * login it verified as (when a verification has happened this session).
 */
export type ForgeAuth = { 
/**
 * `None` — no token anywhere; the UI offers connecting.
 */
source: TokenSource | null, 
/**
 * GitHub login the token last verified as, when known.
 */
login: string | null, };
