// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForgeProvider } from "./ForgeProvider";

/**
 * The forge-side identity of a repository, derived from one git remote.
 */
export type ForgeRepo = { provider: ForgeProvider, 
/**
 * Name of the git remote this was derived from (e.g. "origin").
 */
remote: string, 
/**
 * Forge host (e.g. "github.com", or a GitHub Enterprise host).
 */
host: string, owner: string, name: string, };
