// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForgeProvider } from "./ForgeProvider";

export type ForgeCapabilities = { provider: ForgeProvider, supportsPrStacks: boolean, supportsAutoLand: boolean, };
