// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One configured git remote, as `git remote -v` would list it.
 */
export type GitRemote = { name: string, url: string, };
