// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";

export type GraphNode = { 
/**
 * JJ change id (stable across rewrites).
 */
id: string, commitId: string, 
/**
 * Empty string when the change has no description yet.
 */
description: string, author: string, 
/**
 * RFC 3339 timestamp.
 */
timestamp: string, kind: NodeKind, 
/**
 * Parent change ids, limited to parents present in the snapshot.
 */
parents: Array<string>, 
/**
 * Closest snapshot ancestors reachable only through history the
 * snapshot omits (jj's `~` elided revisions). Disjoint from
 * `parents`; set on immutable bases so the trunk line stays one
 * connected spine.
 */
elidedParents: Array<string>, bookmarks: Array<string>, isEmpty: boolean, hasConflict: boolean, };
