// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NodeKind } from "./NodeKind";

export type GraphNode = { 
/**
 * Unique node id — what selection and every backend request use. The
 * short change id (stable across rewrites) normally; for a divergent
 * change (several visible commits share one change id) each commit
 * keys by its short *commit* id instead, jj's own addressing rule for
 * divergence. The two namespaces never collide: jj renders change ids
 * in reverse hex (k–z) and commit ids in forward hex (0–9a–f).
 */
id: string, 
/**
 * Short change id, for display. Equals `id` except on divergent nodes.
 */
changeId: string, commitId: string, 
/**
 * Empty string when the change has no description yet.
 */
description: string, author: string, 
/**
 * RFC 3339 timestamp.
 */
timestamp: string, kind: NodeKind, 
/**
 * Parent change ids, limited to parents present in the snapshot.
 */
parents: Array<string>, 
/**
 * Closest snapshot ancestors reachable only through history the
 * snapshot omits (jj's `~` elided revisions). Disjoint from
 * `parents`; set on immutable bases so the trunk line stays one
 * connected spine.
 */
elidedParents: Array<string>, bookmarks: Array<string>, isEmpty: boolean, hasConflict: boolean, 
/**
 * jj's `??` state: other visible commit(s) share this change id, so
 * the change id no longer names one commit. Rendered first-class; the
 * usual resolution is abandoning or rewriting the copies not wanted.
 */
isDivergent: boolean, };
