// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One reason a land plan cannot act. `wait` says whether waiting alone
 * can clear it: true for remote conditions that settle by themselves
 * (checks running, an approval pending, GitHub still computing
 * mergeability) — what an auto-land job watches through quietly — and
 * false when the user has to act first (a draft, requested changes,
 * failing checks, an unpublished stack).
 */
export type LandBlocker = { message: string, wait: boolean, };
