// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeMethod } from "./MergeMethod";

/**
 * One landing action, in execution order.
 */
export type LandAction = { "kind": "mergePr", number: bigint, bookmark: string, method: MergeMethod, expectedHead: string, } | { "kind": "enableAutoMerge", number: bigint, bookmark: string, method: MergeMethod, } | { "kind": "enqueuePr", number: bigint, bookmark: string, } | { "kind": "fetchRemote", remote: string, } | { "kind": "rebaseOntoTrunk", rootChange: string, moves: number, } | { "kind": "pushStack", bookmarks: Array<string>, } | { "kind": "retargetPr", number: bigint, bookmark: string, toBase: string, } | { "kind": "cleanupBookmark", bookmark: string, } | { "kind": "abandonLanded", bookmark: string, 
/**
 * Newest-first, the order the sweep is applied in.
 */
changeIds: Array<string>, };
