// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LandSegmentStatus } from "./LandSegmentStatus";
import type { PrSummary } from "./PrSummary";

export type LandSegment = { bookmark: string, 
/**
 * Change ids in the segment, bottom-first.
 */
changeIds: Array<string>, 
/**
 * The open PR GitHub has for this bookmark, when one exists.
 */
pr: PrSummary | null, status: LandSegmentStatus, };
