// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a segment stands in the landing story.
 */
export type LandSegmentStatus = { "kind": "merged", number: bigint, url: string, } | { "kind": "landing" } | { "kind": "waiting" } | { "kind": "stacked" };
