// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LandAction } from "./LandAction";
import type { LandBlocker } from "./LandBlocker";
import type { LandSegment } from "./LandSegment";

/**
 * What landing a stack will do this run, derived before anything runs.
 */
export type LandPlan = { headBookmark: string, remote: string, 
/**
 * The trunk branch the stack lands on.
 */
baseBranch: string, 
/**
 * The stack, bottom-up, each segment placed in the landing story.
 */
segments: Array<LandSegment>, 
/**
 * Everything this run will do, in order. Empty with a note in
 * `warnings` means GitHub is already driving (auto-merge enabled, in
 * the merge queue) and there is nothing to do but wait.
 */
actions: Array<LandAction>, 
/**
 * Problems that stop this run from doing anything.
 */
blockers: Array<LandBlocker>, warnings: Array<string>, };
