// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LandAction } from "./LandAction";
import type { SubmitStepStatus } from "./SubmitStepStatus";

export type LandStep = { action: LandAction, status: SubmitStepStatus, 
/**
 * Plain-language result: what happened, or why it was skipped.
 */
detail: string | null, };
