// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a PR merges into its base. GitHub's three; when several are allowed
 * the plan prefers squash (jjpr's default and the stacked-PR convention),
 * then rebase, then a merge commit.
 */
export type MergeMethod = "squash" | "rebase" | "merge";
