// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a mutation did, surfaced as the operation breadcrumb after the
 * snapshot refreshes. Every write action returns one.
 */
export type MutationOutcome = { 
/**
 * Short hex id of the jj operation this mutation recorded; `None` when
 * the request was a no-op and nothing changed.
 */
operationId: string | null, 
/**
 * Plain-language description of what happened, e.g. "Described pqsrwxyz".
 */
summary: string, 
/**
 * Change id the workbench selection should follow after the refresh:
 * the new working copy for `new`, the parent after abandon/squash, the
 * target itself otherwise.
 */
targetChange: string | null, };
