// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpEffectKind } from "./OpEffectKind";

export type OpEffect = { kind: OpEffectKind, 
/**
 * E.g. "main moved", "main@origin updated", "working copy moved".
 */
label: string, };
