// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpEffect } from "./OpEffect";

export type OperationItem = { id: string, description: string, 
/**
 * RFC 3339 timestamp.
 */
timestamp: string, isCurrent: boolean, 
/**
 * `user@host` that recorded the operation.
 */
user: string, 
/**
 * Pure working-copy snapshot operations; the timeline renders them
 * quieter and collapses runs of them.
 */
isSnapshot: boolean, 
/**
 * Plain-language summaries of what changed vs the parent operation.
 * Bookmark moves are reported at change-id granularity, so a rewrite
 * that keeps a bookmark on the same change is not a "move".
 */
effects: Array<OpEffect>, 
/**
 * Count of effects dropped past the per-operation cap.
 */
moreEffects: number, };
