// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrSummary } from "./PrSummary";

/**
 * The open-PR state of one repository.
 */
export type PrStateReport = { prs: Array<PrSummary>, 
/**
 * True when the repo has more open PRs than the one batched query
 * returns (capped at 100, newest-updated first).
 */
truncated: boolean, };
