// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChecksRollup } from "./ChecksRollup";
import type { PrState } from "./PrState";
import type { ReviewDecision } from "./ReviewDecision";

/**
 * One pull request's review-relevant state.
 */
export type PrSummary = { number: bigint, title: string, 
/**
 * Web URL of the PR.
 */
url: string, state: PrState, isDraft: boolean, 
/**
 * Branch the PR merges from — the pushed bookmark's name.
 */
headBranch: string, 
/**
 * Full commit id of the PR's current head.
 */
headCommit: string, 
/**
 * Owner of the repo the head branch lives in; differs from the base
 * repo's owner for cross-fork PRs, `None` when the fork is gone.
 */
headOwner: string | null, baseBranch: string, review: ReviewDecision, checks: ChecksRollup, };
