// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookmarkState } from "./BookmarkState";
import type { ConflictItem } from "./ConflictItem";
import type { GitRemote } from "./GitRemote";
import type { GraphNode } from "./GraphNode";
import type { OperationItem } from "./OperationItem";
import type { WorkspaceSummary } from "./WorkspaceSummary";
import type { WorkstreamSummary } from "./WorkstreamSummary";

export type RepoSnapshot = { repoPath: string, repoName: string, 
/**
 * Which backend produced this snapshot ("jj-lib", or "mock" when the
 * app runs with the mock backend).
 */
backend: string, trunkBookmark: string, 
/**
 * Change id of the current working-copy node.
 */
workingCopy: string, workspaces: Array<WorkspaceSummary>, workstreams: Array<WorkstreamSummary>, nodes: Array<GraphNode>, bookmarks: Array<BookmarkState>, 
/**
 * The repo's configured git remotes (jj's hidden colocated `git`
 * remote excluded). Forge detection — which GitHub project does this
 * repo publish to — reads these; `jiji-core` itself only reports them.
 */
gitRemotes: Array<GitRemote>, conflicts: Array<ConflictItem>, 
/**
 * Newest first.
 */
operations: Array<OperationItem>, 
/**
 * The external merge tool a Resolve action would launch, by its
 * configured name ("smerge", "meld", …): the user's `ui.merge-editor`,
 * or Sublime Merge when nothing is configured and it is installed.
 * `None` hides Resolve affordances — no usable tool is configured.
 */
resolveTool: string | null, };
