// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookmarkState } from "./BookmarkState";
import type { ConflictItem } from "./ConflictItem";
import type { GraphNode } from "./GraphNode";
import type { OperationItem } from "./OperationItem";
import type { WorkspaceSummary } from "./WorkspaceSummary";
import type { WorkstreamSummary } from "./WorkstreamSummary";

export type RepoSnapshot = { repoPath: string, repoName: string, 
/**
 * Which backend produced this snapshot ("jj-lib", or "mock" when the
 * app runs with the mock backend).
 */
backend: string, trunkBookmark: string, 
/**
 * Change id of the current working-copy node.
 */
workingCopy: string, workspaces: Array<WorkspaceSummary>, workstreams: Array<WorkstreamSummary>, nodes: Array<GraphNode>, bookmarks: Array<BookmarkState>, conflicts: Array<ConflictItem>, 
/**
 * Newest first.
 */
operations: Array<OperationItem>, };
