// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrStateReport } from "./PrStateReport";
import type { PrSummary } from "./PrSummary";

/**
 * The open-PR answer as the UI consumes it: the report plus its
 * bookmark-attachment view — head branch → PR, fork-filtered via
 * [`prs_by_branch`], so a local bookmark's badge is one map lookup.
 */
export type RepoPrState = { report: PrStateReport, byBranch: { [key in string]?: PrSummary }, };
