// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GitHub's `reviewDecision`: `None` when the repo does not require reviews.
 */
export type ReviewDecision = "approved" | "changesRequested" | "reviewRequired" | "none";
