// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShipAction } from "./ShipAction";

/**
 * What shipping a stack to trunk will do, derived before anything runs.
 */
export type ShipPlan = { 
/**
 * The stack head being shipped (a snapshot node id).
 */
headChange: string, 
/**
 * First line of the head's description, for the panel.
 */
headTitle: string, trunkBookmark: string, remote: string, 
/**
 * The shipped chain, bottom-up (first parents from trunk to head).
 */
changeIds: Array<string>, 
/**
 * Everything this run will do, in order. Empty with no blockers
 * means the stack is already shipped — submit's idempotence.
 */
actions: Array<ShipAction>, 
/**
 * Problems that stop the plan from running at all.
 */
blockers: Array<string>, warnings: Array<string>, };
