// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One shipping action, in execution order.
 */
export type ShipAction = { "kind": "rebaseOntoTrunk", rootChange: string, moves: number, } | { "kind": "moveTrunk", bookmark: string, to: string, } | { "kind": "pushTrunk", bookmark: string, remote: string, } | { "kind": "newWorkingCopy", on: string, };
