// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShipStep } from "./ShipStep";

export type ShipOutcome = { steps: Array<ShipStep>, failed: boolean, };
