// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitHunk } from "./SplitHunk";

/**
 * One file's part in a split: either the whole file (the fast path) or a
 * subset of its diff hunks. What the split panel sends per checked row.
 */
export type SplitSelection = { 
/**
 * Repo-relative path, `/`-separated.
 */
path: string, 
/**
 * `None` — the whole file moves into the carved-off change. `Some` —
 * only these hunks of the file's current diff do; the rest of the file
 * stays with the remainder. Hunks are identified by their unified-diff
 * coordinates so the backend can verify them against a freshly
 * computed diff and refuse when the change moved underneath the panel.
 */
hunks: Array<SplitHunk> | null, };
