// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Coordinates of one selected unified hunk, as the diff surface rendered
 * it: 1-based start lines plus the per-side line counts (context lines
 * included). A hunk that no longer matches these exactly is refused.
 */
export type SplitHunk = { oldStart: number, newStart: number, oldLines: number, newLines: number, };
