// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrSummary } from "./PrSummary";
import type { SubmitAction } from "./SubmitAction";
import type { SubmitStepStatus } from "./SubmitStepStatus";

export type SubmitStep = { action: SubmitAction, status: SubmitStepStatus, 
/**
 * Plain-language result: the push summary, or the failure message.
 */
detail: string | null, 
/**
 * The PR a `CreatePr` step opened, for linking out.
 */
pr: PrSummary | null, };
