// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmitAction } from "./SubmitAction";
import type { SubmitSegment } from "./SubmitSegment";

/**
 * What submitting a stack will do, derived before anything runs.
 */
export type SubmitPlan = { 
/**
 * The bookmark the plan publishes up to (the stack's top bookmark).
 */
headBookmark: string, 
/**
 * Git remote the pushes go to — the detected forge repo's remote.
 */
remote: string, 
/**
 * The trunk branch the bottom segment's PR targets.
 */
baseBranch: string, 
/**
 * The stack's publishable segments, bottom-up.
 */
segments: Array<SubmitSegment>, 
/**
 * Everything that will run, in order. Empty means up to date.
 */
actions: Array<SubmitAction>, 
/**
 * Problems that stop the plan from running at all (undescribed or
 * conflicted commits in a pushed segment, a conflicted bookmark).
 */
blockers: Array<string>, 
/**
 * Worth knowing, but the plan still runs.
 */
warnings: Array<string>, 
/**
 * The stack-info comment as it will read, rendered for the panel
 * when the plan syncs comments (PRs created by this plan appear as
 * plain names — their links exist only after execution).
 */
stackCommentPreview: string | null, };
