// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PrSummary } from "./PrSummary";

/**
 * One publishable run of changes under a bookmark, listed bottom-up in
 * [`SubmitPlan::segments`]. Mirrors jjpr's segment: the commits between
 * the bookmark below (or trunk) and this segment's bookmark.
 */
export type SubmitSegment = { bookmark: string, 
/**
 * Branch this segment's PR merges into: the trunk branch for the
 * bottom segment, the bookmark below otherwise.
 */
base: string, 
/**
 * Change ids in the segment, bottom-first.
 */
changeIds: Array<string>, 
/**
 * PR title the segment would get (or has): the bottom change's
 * description first line.
 */
title: string, 
/**
 * The open PR GitHub already has for this bookmark, when one exists.
 */
pr: PrSummary | null, };
