// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmitStep } from "./SubmitStep";

export type SubmitOutcome = { steps: Array<SubmitStep>, failed: boolean, };
