// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-action result of executing a plan.
 */
export type SubmitStepStatus = "done" | "failed" | "skipped";
