// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One remote action the plan will run, in execution order.
 */
export type SubmitAction = { "kind": "push", bookmark: string, create: boolean, } | { "kind": "createPr", bookmark: string, base: string, title: string, body: string, } | { "kind": "retargetPr", number: bigint, bookmark: string, fromBase: string, toBase: string, };
