// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the active token came from.
 */
export type TokenSource = "keychain" | "environment" | "ghCli";
