// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One mutable line of work: an ordered chain of dependent changes,
 * optionally published through a bookmark.
 */
export type WorkstreamSummary = { id: string, title: string, 
/**
 * Change ids, top-first. The working copy is included when it sits on
 * top of this stack.
 */
nodeIds: Array<string>, bookmark: string | null, isActive: boolean, behindTrunk: number, };
