// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceSummary = { name: string, isDefault: boolean, 
/**
 * The workspace this snapshot was produced from — the one the app has
 * open, whose staleness is detectable and recoverable. Sibling
 * workspaces keep their working-copy state in their own roots, which
 * this workspace cannot see, so their `is_stale` stays `false`.
 */
isCurrent: boolean, isStale: boolean, workingCopyNode: string | null, };
